CATALOG = {
    "status.ready": "ready",
    "status.running": "running",
    "status.completed": "completed",
    "status.passed": "verification passed",
    "status.blocked": "blocked",
    "status.waiting_permission": "waiting for permission",
    "ui.status": "status",
    "ui.tokens": "tokens",
    "ui.cache": "cache",
    "ui.changed": "changed",
    "ui.none": "none",
    "ui.permissions": "permissions",
    "ui.idle": "idle",
    "ui.on": "on",
    "ui.off": "off",
    "ui.assistant": "Assistant",
    "ui.failure_pack": "Failure",
    "event.turn_started.title": "Started",
    "event.turn_started.message": "Understanding your request.",
    "event.context_built.title": "Context Ready",
    "event.context_built.message": "Prepared context, about {estimated_tokens} tokens (messages {message_estimated_tokens} + tools {tool_schema_tokens}).",
    "event.model_call_started.title": "Calling Model",
    "event.model_call_started.message": "Calling {model}.",
    "event.model_call_finished.title": "Model Returned",
    "event.model_call_finished.message": "Model returned {tool_calls} tool calls.",
    "event.tool_call_started.title": "Running {tool}",
    "event.tool_call_started.message": "Running {tool}.",
    "event.tool_call_finished.ok.title": "{tool} Finished",
    "event.tool_call_finished.ok.message": "{tool} finished.",
    "event.tool_call_finished.failed.title": "{tool} Failed",
    "event.tool_call_finished.failed.message": "{tool} did not complete successfully.{details}",
    "event.command_progress.title": "Command {stage}",
    "event.command_progress.message": "{command} has run for {elapsed_seconds}s, timeout {timeout_seconds}s.",
    "event.file_changed.title": "File Changed",
    "event.file_changed.message": "Changed {path}.",
    "event.verification_started.title": "Verification",
    "event.verification_started.message": "Running project verification.",
    "event.verification_plan_created.title": "Verification Plan",
    "event.verification_plan_created.message": "Strategy: {reason}.",
    "event.verification_step_started.title": "Verification Step",
    "event.verification_step_started.message": "Running {name}.",
    "event.verification_step_finished.ok.title": "Verification Passed",
    "event.verification_step_finished.ok.message": "{name} passed.",
    "event.verification_step_finished.failed.title": "Verification Failed",
    "event.verification_step_finished.failed.message": "{name} failed.{details}",
    "event.verification_needs_model_decision.title": "Verification Needs Model Decision",
    "event.verification_needs_model_decision.message": "Automatic verification paused. The model should choose the next project-specific verification step: {reason}.",
    "event.background_command_started.title": "Starting Server",
    "event.background_command_started.message": "Starting background service on port {port}.",
    "event.background_command_ready.title": "Server Ready",
    "event.background_command_ready.message": "Service is ready on port {port}.",
    "event.background_command_failed.title": "Server Failed",
    "event.background_command_failed.message": "Service on port {port} did not start.",
    "event.failure_pack_created.title": "Blocking Failure",
    "event.failure_pack_created.message": "{first_blocking_failure}",
    "event.repair_round_started.title": "Repair Started",
    "event.repair_round_started.message": "Starting repair round {round}.",
    "event.recoverable_tool_error.title": "Recoverable Tool Error",
    "event.recoverable_tool_error.message": "Tool failed but the session will keep trying: {reason}",
    "event.required_tool_retry.title": "More Tool Work Needed",
    "event.required_tool_retry.message": "This request needs another tool call: {expected_action}.",
    "event.goal_active.title": "Goal Loaded",
    "event.goal_active.message": "Session goal: {objective}; turn relation: {goal_engagement}",
    "event.goal_created.title": "Goal Recorded",
    "event.goal_created.message": "Goal: {objective}",
    "event.goal_updated.title": "Goal Updated",
    "event.goal_updated.message": "Goal status: {status}.",
    "event.goal_turn_finished.title": "Goal Turn Finished",
    "event.goal_turn_finished.message": "Current status: {status}.",
    "event.dependency_install_started.title": "Installing Dependencies",
    "event.dependency_install_started.message": "Running: {command}",
    "event.dependency_install_finished.title": "Dependency Install Finished",
    "event.dependency_install_finished.message": "Command ok: {ok}.",
    "event.dependency_install_skipped.title": "Dependency Install Skipped",
    "event.dependency_install_skipped.message": "{reason}",
    "event.permission_requested.title": "Permission Needed",
    "event.permission_requested.message": "{reason}",
    "event.blocked.title": "Blocked",
    "event.blocked.message": "{reason}",
    "event.turn_finished.title": "Turn Finished",
    "event.turn_finished.message": "Status: {status}.",
    "event.fallback.title": "System Event",
    "event.fallback.message": "{event_type}: {payload}",
    "tool.list_directory": "list directory",
    "tool.read_file": "read file",
    "tool.find_images": "find images",
    "tool.view_image": "view image",
    "tool.write_file": "write file",
    "tool.edit_file": "edit file",
    "tool.delete_file": "delete file",
    "tool.run_command": "run command",
    "tool.run_python": "run Python helper",
    "tool.start_background_command": "start background service",
    "tool.read_background_log": "read background log",
    "tool.remember_workflow": "remember workflow",
    "tool.search_workflows": "search workflows",
    "tool.read_workflow": "read workflow",
    "tool.update_workflow": "update workflow",
    "tool.forget_workflow": "forget workflow",
    "tool.browser_test": "browser test",
    "tool.inspect_port": "inspect port",
    "tool.release_port": "release port",
    "tool.inspect_project_startup": "inspect project startup",
    "tool.inspect_toolchain": "inspect toolchain",
    "tool.install_toolchain": "install toolchain",
    "tool.get_goal": "get goal",
    "tool.get_work_plan": "get work plan",
    "tool.create_goal": "create goal",
    "tool.update_goal": "update goal",
}
